AWSTemplateFormatVersion: '2010-09-09'
Description: Example of Parameters with Allowed Values

Parameters:
  Environment:
    Type: String
    Default: development
    AllowedValues:
      - production
      - staging
      - development
    Description: Select the environment type for the deployment

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub "my-app-${Environment}-bucket-cf-2025"
