AWSTemplateFormatVersion: '2010-09-09'
Description: Example of List Parameters in CloudFormation

Parameters:
  SecurityGroupIds:
    Type: CommaDelimitedList
    Description: List of security group IDs to associate with the EC2 instance
    Default: sg-01b9e3397bbf1788b, sg-09daebbe014187471
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-02457590d33d576c3   #Example AMI ID
      SecurityGroupIds: !Ref SecurityGroupIds