AWSTemplateFormatVersion: '2010-09-09'
Description: Nested Stack for EC2 Instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-09e6f87a47903347c    #Example AMI ID
      KeyName: my-key-pair

Outputs:
   EC2InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref MyEC2Instance