AWSTemplateFormatVersion: '2010-09-09'
Description: A simple CloudFormation template to create an S3 bucket and an EC2 instance.

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.

  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-unique-bucket-name-cf-2025

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: ami-02457590d33d576c3  #Example AMI ID (Amazon Linux 2)
      KeyName: my-key-pair   # Replace with your key pair name
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0   #Allow SSH from anywhere (not recommended for production)

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket
    Value: !Ref MyS3Bucket

  EC2InstanceId:
    Description: The ID of the EC2 instance
    Value: !Ref MyEC2Instance


Outputs:
  S3BucketName:
    Description: The name of the imported S3 bucket
    Value: !Ref MyS3Bucket
  S3BucketArn:
    Description: The ARN of the imported S3 bucket
    Value: !GetAtt MyS3Bucket.Arn