AWSTemplateFormatVersion: '2010-09-09'
Description: Simple web application infrastructure

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: my-stack-set-cf-bucket-2025

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c55b159cbfafe1f0   #Example AMI ID
      KeyName: my-key-pair
      SecurityGroupIds:
        - !Ref MySecurityGroup

  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0

# AWSCloudFormationStackSetAdministrationRole' role with trust relationship to CloudFormation service